create table if not exists public.renewal_message_logs (
  id bigint generated by default as identity primary key,
  customer_id bigint not null references public.customers(id) on delete cascade,
  renewal_date date not null,
  status text not null default 'pending' check (status in ('pending','sent','skipped')),
  sent_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (customer_id, renewal_date)
);

alter table public.renewal_message_logs enable row level security;

drop policy if exists renewal_message_logs_admin_select on public.renewal_message_logs;
create policy renewal_message_logs_admin_select
on public.renewal_message_logs for select to authenticated
using ((auth.jwt() ->> 'email') = 'mezooelzorkany@gmail.com');

drop policy if exists renewal_message_logs_admin_insert on public.renewal_message_logs;
create policy renewal_message_logs_admin_insert
on public.renewal_message_logs for insert to authenticated
with check ((auth.jwt() ->> 'email') = 'mezooelzorkany@gmail.com');

drop policy if exists renewal_message_logs_admin_update on public.renewal_message_logs;
create policy renewal_message_logs_admin_update
on public.renewal_message_logs for update to authenticated
using ((auth.jwt() ->> 'email') = 'mezooelzorkany@gmail.com')
with check ((auth.jwt() ->> 'email') = 'mezooelzorkany@gmail.com');

drop policy if exists renewal_message_logs_admin_delete on public.renewal_message_logs;
create policy renewal_message_logs_admin_delete
on public.renewal_message_logs for delete to authenticated
using ((auth.jwt() ->> 'email') = 'mezooelzorkany@gmail.com');
